#!/bin/sh

set -e

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so libblas.so-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/blas/libblas.so 10 \
                    --slave /usr/lib/x86_64-linux-gnu/libblas.a libblas.a-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/blas/libblas.a \
                    --slave /usr/include/x86_64-linux-gnu/cblas.h cblas.h-x86_64-linux-gnu \
                    /usr/include/x86_64-linux-gnu/cblas-netlib.h \
                    --slave /usr/lib/x86_64-linux-gnu/pkgconfig/blas.pc \
                    blas.pc-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/pkgconfig/blas-netlib.pc



exit 0
